# Generated by Django 6.1 on 2026-08-27 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteSecretariaRiesgo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(default='RF-NU-0014', max_length=20)),
                ('nivel_riesgo', models.CharField(max_length=50)),
                ('tipo_intervencion', models.CharField(max_length=150)),
                ('fuente_reporte', models.CharField(max_length=100)),
                ('zona_territorial', models.CharField(default='Popayán', max_length=100)),
                ('fecha_registro', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='RevisionSecretaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(default='RF-NU-0013', max_length=20)),
                ('usuario_en_riesgo', models.CharField(max_length=150)),
                ('informe_asociado', models.CharField(max_length=200)),
                ('estado_revision', models.CharField(default='Pendiente', max_length=50)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_revision', models.DateField()),
            ],
        ),
    ]
