# Generated by Django 6.1 on 2026-08-28 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InformeAtencion',
            fields=[
                ('id_informe', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_atencion', models.DateTimeField(auto_now_add=True)),
                ('tipo_atencion', models.CharField(max_length=100)),
                ('profesional', models.CharField(max_length=100)),
                ('zona_geografica', models.CharField(max_length=100)),
                ('usuario', models.CharField(max_length=100)),
                ('resumen', models.TextField()),
            ],
        ),
    ]
