# Generated by Django 6.1 on 2026-08-27 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AtencionMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
                ('tipo_atencion', models.CharField(choices=[('general', 'Medicina General'), ('urgencias', 'Urgencias'), ('especializada', 'Consulta Especializada')], max_length=50)),
                ('profesional', models.CharField(choices=[('dr_perez', 'Dr. Carlos Pérez'), ('dra_gomez', 'Dra. Ana Gómez')], max_length=50)),
                ('municipio', models.CharField(default='Popayán', max_length=100)),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='CasoRiesgo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edad', models.IntegerField()),
                ('nivel_riesgo', models.CharField(choices=[('critico', 'Crítico'), ('alto', 'Alto'), ('medio', 'Medio'), ('bajo', 'Bajo')], max_length=20)),
                ('estado_caso', models.CharField(choices=[('abierto', 'Abierto'), ('seguimiento', 'En Seguimiento'), ('cerrado', 'Cerrado')], max_length=30)),
                ('fecha_registro', models.DateField()),
            ],
        ),
    ]
