# Generated by Django 6.1 on 2026-08-28 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_sebas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatGrupal',
            fields=[
                ('id_chat', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_grupo', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats_creados', to='app_sebas.profesional')),
            ],
        ),
        migrations.CreateModel(
            name='MensajeChat',
            fields=[
                ('id_mensaje', models.AutoField(primary_key=True, serialize=False)),
                ('contenido', models.TextField()),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_sebas.profesional')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='app_chat.chatgrupal')),
            ],
        ),
    ]
