# Generated by Django 6.0.7 on 2026-08-24 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AtencionSalud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solicitud_usuario', models.TextField(verbose_name='Solicitud del usuario')),
                ('historia_clinica', models.TextField(verbose_name='Información clínica básica / Antecedentes')),
                ('evaluacion_inicial', models.TextField(verbose_name='Resultados de evaluaciones iniciales')),
                ('reporte_valoracion', models.TextField(verbose_name='Reporte de valoración psicológica o en salud')),
                ('plan_tratamiento', models.TextField(verbose_name='Plan de intervención o tratamiento')),
                ('estrategias_prevencion', models.TextField(verbose_name='Estrategias de prevención y recomendaciones')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('profesional', models.CharField(max_length=150, verbose_name='Profesional a cargo')),
            ],
        ),
    ]
