# Generated by Django 6.0.7 on 2026-08-25 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cristian', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionEmergencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_emergencia', models.CharField(default='123', max_length=20, verbose_name='Número de Línea de Emergencia')),
                ('activo', models.BooleanField(default=True, verbose_name='Línea Disponible')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroLlamadaEmergencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('numero_marcado', models.CharField(max_length=20)),
                ('estado', models.CharField(default='Efectiva', max_length=50)),
            ],
        ),
    ]
