# Generated by Django 6.1 on 2026-08-24 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluacionEmocional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=100)),
                ('profesional', models.CharField(max_length=100)),
                ('estado_afectivo', models.CharField(max_length=100)),
                ('nivel_riesgo', models.CharField(max_length=50)),
                ('necesidades_detectadas', models.TextField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('recomendaciones', models.TextField(blank=True, null=True)),
                ('fecha_evaluacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UbicacionPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paciente', models.CharField(max_length=100)),
                ('latitud', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitud', models.DecimalField(decimal_places=7, max_digits=10)),
                ('autorizacion', models.BooleanField(default=False)),
                ('motivo', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha_ubicacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
